export let ROLE_SUPER_ADMIN = 'superuser'
export let ROLE_ADMIN = 'admin'
export let ROLE_STAFF = 'staff'
export let ROLE_STUDENT = 'student'
export let ROLE_TEACHER = 'teacher'
export let ROLE_PARENT = 'parent'


export let PERMISSION_ALL = 'all'

export let PERMISSION_ADD_STUDENT = 'add student'
export let PERMISSION_CHANGE_STUDENT = 'change student'
export let PERMISSION_VIEW_STUDENT = 'view student'
export let PERMISSION_DELETE_STUDENT = 'delete student'

export let PERMISSION_ADD_SCHOOL = 'add school'
export let PERMISSION_CHANGE_SCHOOL = 'change school'
export let PERMISSION_VIEW_SCHOOL = 'view school'
export let PERMISSION_DELETE_SCHOOL = 'delete school'

export let PERMISSION_ADD_BRANCH = 'add branch'
export let PERMISSION_CHANGE_BRANCH = 'change branch'
export let PERMISSION_VIEW_BRANCH = 'view branch'
export let PERMISSION_DELETE_BRANCH = 'delete branch'

export let PERMISSION_ADD_CLASS = 'add class'
export let PERMISSION_CHANGE_CLASS = 'change class'
export let PERMISSION_VIEW_CLASS = 'view class'
export let PERMISSION_DELETE_CLASS = 'delete class'

export let PERMISSION_ADD_PARENT = 'add parent'
export let PERMISSION_CHANGE_PARENT = 'change parent'
export let PERMISSION_VIEW_PARENT = 'view parent'
export let PERMISSION_DELETE_PARENT = 'delete parent'

export let PERMISSION_ADD_TEACHER = 'add teacher'
export let PERMISSION_CHANGE_TEACHER = 'change teacher'
export let PERMISSION_VIEW_TEACHER = 'view teacher'
export let PERMISSION_DELETE_TEACHER = 'delete teacher'

export let PERMISSION_ADD_USER = 'add user'
export let PERMISSION_CHANGE_USER = 'change user'
export let PERMISSION_VIEW_USER = 'view user'
export let PERMISSION_DELETE_USER = 'delete user'


export let STUDENT_PERMISSIONS = [
    PERMISSION_VIEW_STUDENT,
    PERMISSION_CHANGE_STUDENT
]

export let PARENT_PERMISSIONS = [
    PERMISSION_VIEW_PARENT,
    PERMISSION_VIEW_STUDENT,
    PERMISSION_CHANGE_PARENT
]

export let TEACHER_PERMISSIONS = [
    PERMISSION_VIEW_STUDENT,
    PERMISSION_VIEW_TEACHER,
    PERMISSION_CHANGE_TEACHER
]

export let ADMIN_ONLY_PERMISSIONS = [
    PERMISSION_ADD_STUDENT,
    PERMISSION_CHANGE_STUDENT,
    PERMISSION_VIEW_STUDENT,
    PERMISSION_DELETE_STUDENT,

    PERMISSION_ADD_SCHOOL,
    PERMISSION_CHANGE_SCHOOL,
    PERMISSION_VIEW_SCHOOL,
    PERMISSION_DELETE_SCHOOL,

    PERMISSION_ADD_BRANCH,
    PERMISSION_CHANGE_BRANCH,
    PERMISSION_VIEW_BRANCH,
    PERMISSION_DELETE_BRANCH,

    PERMISSION_ADD_CLASS,
    PERMISSION_CHANGE_CLASS,
    PERMISSION_VIEW_CLASS,
    PERMISSION_DELETE_CLASS,

    PERMISSION_ADD_PARENT,
    PERMISSION_CHANGE_PARENT,
    PERMISSION_VIEW_PARENT,
    PERMISSION_DELETE_PARENT,

    PERMISSION_ADD_TEACHER,
    PERMISSION_CHANGE_TEACHER,
    PERMISSION_VIEW_TEACHER,
    PERMISSION_DELETE_TEACHER,
]

export let ALL_PERMISSIONS = [
    {name: PERMISSION_ADD_BRANCH },
    {name: PERMISSION_ADD_CLASS},
    {name: PERMISSION_ADD_PARENT},
    {name: PERMISSION_ADD_SCHOOL},
    {name: PERMISSION_ADD_STUDENT},
    {name: PERMISSION_ADD_TEACHER},
    {name: PERMISSION_ADD_USER},

    {name: PERMISSION_ALL},

    {name: PERMISSION_CHANGE_BRANCH},
    {name: PERMISSION_CHANGE_CLASS},
    {name: PERMISSION_CHANGE_PARENT},
    {name: PERMISSION_CHANGE_SCHOOL},
    {name: PERMISSION_CHANGE_STUDENT},
    {name: PERMISSION_CHANGE_TEACHER},
    {name: PERMISSION_CHANGE_USER},

    {name: PERMISSION_DELETE_BRANCH},
    {name: PERMISSION_DELETE_CLASS},
    {name: PERMISSION_DELETE_PARENT},
    {name: PERMISSION_DELETE_SCHOOL},
    {name: PERMISSION_DELETE_STUDENT},
    {name: PERMISSION_DELETE_TEACHER},
    {name: PERMISSION_DELETE_USER},

    {name: PERMISSION_VIEW_BRANCH},
    {name: PERMISSION_VIEW_CLASS},
    {name: PERMISSION_VIEW_PARENT},
    {name: PERMISSION_VIEW_SCHOOL},
    {name: PERMISSION_VIEW_STUDENT},
    {name: PERMISSION_VIEW_TEACHER},
    {name: PERMISSION_VIEW_USER}
]